### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by ivanporras** [odoocr/l10n_cr#215]
###### Impacted versions:
* 13

###### Steps to reproduce:
* Vaya a la compañia y presione el boton TEST GET TOKEN

###### Current behavior:
* 2020-11-25 22:52:55,510 32873 ERROR gruposmc-2020-11-25 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/ivan/Documents/ODOO/odoo-13.0/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/ivan/Documents/ODOO/odoo-13.0/custom/addons/grupo-smc/electronic_invoice/cr_electronic_invoice/models/res_company.py", line 156, in test_get_token
    token_m_h = api_facturae.get_token_hacienda(
  File "/home/ivan/Documents/ODOO/odoo-13.0/custom/addons/grupo-smc/electronic_invoice/cr_electronic_invoice/models/api_facturae.py", line 218, in get_token_hacienda
    response_json = response.json()
  File "/home/ivan/Documents/ODOO/odoo-13.0/venv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

###### Expected behavior:
* Deberia obtener el token

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by ivanporras** [comment]
Parece ser una falla de hacienda
![Screenshot(172)](https://user-images.githubusercontent.com/13451948/100290804-ca661700-2f41-11eb-93b7-814b6857af24.png)
![Screenshot(171)](https://user-images.githubusercontent.com/13451948/100290809-ce923480-2f41-11eb-9fee-d901fd4c3c00.png)

**Comment by ivanporras** [comment]
Error de hacienda
