### ISSUE TITLE
Intento de Instalación Módulo Costa Rica Electronic Invoices Odoo V14 Windows 

### ISSUE THREAD

**Issue by tooness** [odoocr/l10n_cr#284]
###### Impacted versions:
* Odoo V14 

###### Steps to reproduce:
* Instale las dependencias de Python, y el Modulo en Odoo

###### Current behavior:
*Durante la instalación del modulo

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\web\controllers\main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\web\controllers\main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\base\models\ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\base\models\ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\modules\loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\modules\loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\modules\loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\modules\module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\__init__.py", line 3, in <module>
    from . import models
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\models\__init__.py", line 3, in <module>
    from . import account_journal
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\models\account_journal.py", line 5, in <module>
    from . import api_facturae
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\models\api_facturae.py", line 37, in <module>
    from .. import extensions
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\extensions\__init__.py", line 3, in <module>
    from . import response_validator
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\addons\cr_electronic_invoice\extensions\response_validator.py", line 3, in <module>
    from jsonschema import validate
  File "C:\Program Files\Odoo 14.0.20220323\python\lib\site-packages\jsonschema\__init__.py", line 12, in <module>
    from jsonschema._format import (
  File "C:\Program Files\Odoo 14.0.20220323\python\lib\site-packages\jsonschema\_format.py", line 10, in <module>
    from jsonschema.exceptions import FormatError
  File "C:\Program Files\Odoo 14.0.20220323\python\lib\site-packages\jsonschema\exceptions.py", line 13, in <module>
    from jsonschema import _utils
  File "C:\Program Files\Odoo 14.0.20220323\python\lib\site-packages\jsonschema\_utils.py", line 12, in <module>
    import importlib_resources as resources  # type: ignore
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20220323\server\odoo\http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ModuleNotFoundError: No module named 'importlib_resources'

###### Expected behavior:
*

###### Video/Screenshot link (optional):

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by tooness** [comment]
Resolví las dependencias que faltaban de Python, pero al montar los datos de demostración, da error y no concluye!

![image](https://user-images.githubusercontent.com/102319346/159982963-19ddfbb0-ac66-4769-adbb-74fbb19c260b.png)

**Comment by EstebanMonge** [comment]
Puede probar con la ultima version del código?

**Comment by ruiznorlan** [comment]
El error es debido a los datos de prueba de Odoo, puede intentar actualizando su versión de Odoo a la más reciente o corrigiendo el error en el fichero "sale_order_demo.xml" del módulo de "sale_stock", no es un problema del modulo de facturación electrónica, por lo que voy a marcar como cerrado el issue
