### ISSUE TITLE
Error al validar facturas con impuestos ESPECIALES

### ISSUE THREAD

**Issue by rlsoluttionscr** [odoocr/l10n_cr#305]
###### Impacted versions:
* 
Odoo V12
###### Steps to reproduce:
* 
Validación de Facturas de compras
###### Current behavior:
*
Durante consulta de Factura de Proveedor
###### Expected behavior:
*
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/[pycompat.py](http://pycompat.py/)", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/[model.py](http://model.py/)", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 941, in call
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/[http.py](http://http.py/)", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/[main.py](http://main.py/)", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/[main.py](http://main.py/)", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/[api.py](http://api.py/)", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/[api.py](http://api.py/)", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/addons/l10n_cr/cr_electronic_invoice/models/account_invoice.py", line 949, in action_check_hacienda
    False, False)
  File "/opt/odoo12/addons/l10n_cr/cr_electronic_invoice/models/api_facturae.py", line 886, in consulta_documentos
    clave = inv.number_electronic + "-" + inv.consecutive_number_receiver
TypeError: must be str, not bool

###### Video/Screenshot link (optional):

https://imgur.com/7CxgP9J

https://imgur.com/1ZJmcg6

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by rlsoluttionscr** [comment]
Al validar ciertas facturas y consultarlas marca el anterior error adjunta screenshots de detalles de factura.

**Comment by rlsoluttionscr** [comment]
Aplica también con facturas del ICE con impuestos especiales ( 911-CRUZROJA )
