### ISSUE TITLE
Error Validacion Hacienda POS V 12.0

### ISSUE THREAD

**Issue by lmoram** [odoocr/l10n_cr#306]
###### Impacted versions:
12.0
###### Steps to reproduce:
Validacion Hacienda POS

###### Video/Screenshot link (optional):
[error.txt](https://github.com/odoocr/l10n_cr/files/8871835/error.txt)

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by nehemiascr** [comment]
```python
Error:
 Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo12/odoo/tools/safe_eval.py", line 352, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo12/extra-addons/l10n_cr/cr_electronic_invoice_pos/models/electronic_invoice.py", line 683, in _validahacienda_pos
    fecha_emision_referencia, codigo_referencia, razon_referencia)
  File "/home/odoo/odoo12/extra-addons/l10n_cr/cr_electronic_invoice/models/api_facturae.py", line 506, in gen_xml_v43
    for (k, v) in lines.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo12/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo12/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo12/odoo/addons/base/models/ir_cron.py", line 83, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "/home/odoo/odoo12/odoo/addons/base/models/ir_actions.py", line 546, in run
    res = func(action, eval_context=eval_context)
  File "/home/odoo/odoo12/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/home/odoo/odoo12/odoo/addons/base/models/ir_actions.py", line 437, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/odoo12/odoo/tools/safe_eval.py", line 375, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/odoo/odoo12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo12/odoo/tools/safe_eval.py", line 352, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo12/extra-addons/l10n_cr/cr_electronic_invoice_pos/models/electronic_invoice.py", line 683, in _validahacienda_pos
    fecha_emision_referencia, codigo_referencia, razon_referencia)
  File "/home/odoo/odoo12/extra-addons/l10n_cr/cr_electronic_invoice/models/api_facturae.py", line 506, in gen_xml_v43
    for (k, v) in lines.items():
ValueError: <class 'AttributeError'>: "'str' object has no attribute 'items'" while evaluating
'model._validahacienda_pos(20)'
```
