### ISSUE TITLE
Error Validacion Hacienda POS V 14.0

### ISSUE THREAD

**Issue by lmoram** [odoocr/l10n_cr#310]
###### Impacted versions:
14.0

###### Steps to reproduce:
Validacion Hacienda POS
###### Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo14/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo14/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_cron.py", line 83, in method_direct_trigger
    cron.with_user(cron.user_id).with_context(lastcall=cron.lastcall).ir_actions_server_id.run()
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo14/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo14/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'TypeError'>: "can only concatenate str (not "bool") to str" while evaluating
'model._validahacienda_pos(20)'

[Link or URL](https://github.com/odoocr/l10n_cr)

**Comment by lmoram** [comment]
Se realiza instlación limpia y no genera el error
