### ISSUE TITLE
[14.0] Error al cargar facturas de Proveedor 

### ISSUE THREAD

**Issue by lmoram** [odoocr/l10n_cr#319]
###### Impacted versions:
14

###### Steps to reproduce:
Al tratar de cargar las facturas de los proveedores genera error, no crea el proveedor de forme automática
###### Current behavior:
Al tratar de cargar las facturas de los proveedores genera error, no crea el proveedor de forme automática

###### Expected behavior:
Cargar ls lineas de facturas de proveedor creando el proveedor de forma automática si no existe.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo14/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo14/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo14/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo14/odoo/models.py", line 3022, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo14/odoo/models.py", line 3042, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo14/odoo/models.py", line 5687, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo14/odoo/fields.py", line 2485, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/odoo14/odoo/fields.py", line 1028, in __get__
    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo14/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo14/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Compute method failed to assign account.move(38,).economic_activities_ids

**Comment by lmoram** [comment]
Si el proveedor esta creado de forma previa y manual no genera el error.
